import{A as v,S as L,i as w}from"./assets/vendor-db5ad915.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const m=v.create({baseURL:"https://pixabay.com",params:{key:"42310325-d8e2b88bd4f4d7db9639050a5",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:1}});let E=new L(".image-link",{captionsData:"alt",captionDelay:250});const q=document.querySelector(".form"),p=document.querySelector(".input-name"),l=document.querySelector(".loader"),S=document.querySelector(".gallery"),d=document.querySelector(".load-btn");let n=1,u="",f=0;q.addEventListener("submit",P);async function P(o){o.preventDefault();const t=p.value.trim();if(t===""){c("Please enter a search query");return}t!==u&&(n=1,u=t),l.classList.add("visible");try{const i=(await m.get("/api/",{params:{q:t,page:n}})).data;f=i.totalHits,h(i.hits)}catch(s){c("Error fetching data"),console.log("Error fetching data:",s)}finally{l.classList.remove("visible")}}d.addEventListener("click",$);async function $(){const o=p.value.trim();l.classList.add("visible");try{const s=(await m.get("/api/",{params:{q:o,page:n+1}})).data;h(s.hits),n+=1}catch(t){c("Error fetching more data"),console.log("Error fetching more data:",t)}finally{l.classList.remove("visible")}}function c(o){w.show({title:"Error",message:o})}function x(o,t,s,i,e,r,a){return`<li class="photo">
    <div class="photo-card">
      <a class="image-link" data-lightbox="image" href="${t}">
        <img class="gallery-image" data-source="${t}" src="${o}" alt="${s}"></img>
      </a>
    </div>
    <div class="description">
      <p class="description-item"> Likes ${i}</p>
      <p class="description-item"> Views ${e}</p>
      <p class="description-item"> Comments ${r}</p>
      <p class="description-item"> Downloads ${a}</p>
    </div>
  </li>`}function h(o){o.length===0&&c("Sorry, there are no images matching your search query. Please try again!"),o.forEach(t=>{const{webformatURL:s,largeImageURL:i,tags:e,likes:r,views:a,comments:y,downloads:g}=t,b=x(s,i,e,r,a,y,g);S.insertAdjacentHTML("beforeend",b)}),E.refresh(),O()}function O(){n*15<f?d.style.visibility="visible":(d.style.visibility="hidden",c("Cannot visualize more images"))}
//# sourceMappingURL=commonHelpers.js.map
