import{A as w,S as q,i as S}from"./assets/vendor-db5ad915.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const h=w.create({baseURL:"https://pixabay.com",params:{key:"42310325-d8e2b88bd4f4d7db9639050a5",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:1}});let P=new q(".image-link",{captionsData:"alt",captionDelay:250});const y=document.querySelector(".form"),c=document.querySelector(".input-name"),d=document.querySelector(".loader"),p=document.querySelector(".gallery"),u=document.querySelector(".load-btn");let n=1,f="",m=0;y.addEventListener("submit",$);async function $(o){o.preventDefault();const t=c.value.trim();if(t===""){l("Please enter a search query");return}t!==f&&(n=1,f=t),d.classList.add("visible");try{const i=(await h.get("/api/",{params:{q:t,page:n}})).data;m=i.totalHits,g(i.hits)}catch(s){l("Error fetching data"),console.log("Error fetching data:",s)}finally{d.classList.remove("visible")}}u.addEventListener("click",M);async function M(){const o=c.value.trim();d.classList.add("visible");try{const s=(await h.get("/api/",{params:{q:o,page:n+1}})).data;g(s.hits),n+=1}catch(t){l("Error fetching more data"),console.log("Error fetching more data:",t)}finally{d.classList.remove("visible")}}function l(o){S.show({title:"Error",message:o,position:"center"})}function x(o,t,s,i,e,r,a){return`<li class="photo">
    <div class="photo-card">
      <a class="image-link" data-lightbox="image" href="${t}">
        <img class="gallery-image" data-source="${t}" src="${o}" alt="${s}"></img>
      </a>
    </div>
    <div class="description">
      <p class="description-item"> Likes ${i}</p>
      <p class="description-item"> Views ${e}</p>
      <p class="description-item"> Comments ${r}</p>
      <p class="description-item"> Downloads ${a}</p>
    </div>
  </li>`}function g(o){p.innerHTML="",o.length===0&&l("Sorry, there are no images matching your search query. Please try again!"),o.forEach(t=>{const{webformatURL:s,largeImageURL:i,tags:e,likes:r,views:a,comments:b,downloads:L}=t,E=x(s,i,e,r,a,b,L);p.insertAdjacentHTML("beforeend",E)}),P.refresh(),O()}function O(){n*15<m&&n<=Math.ceil(m/15)?u.style.visibility="visible":(u.style.visibility="hidden",l("Cannot visualize more images"))}c.addEventListener("input",v);function v(){const o=document.querySelector(".iziToast");o&&o.remove()}y.addEventListener("submit",()=>{v(),c.value=c.value.trim()});
//# sourceMappingURL=commonHelpers.js.map
