import{A as b,S as v,i as n}from"./assets/vendor-db5ad915.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const u=b.create({baseURL:"https://pixabay.com",params:{key:"42310325-d8e2b88bd4f4d7db9639050a5",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:1}});let L=new v(".image-link",{captionsData:"alt",captionDelay:250});const m=document.querySelector(".form"),w=document.querySelector(".input-name"),c=document.querySelector(".loader"),p=document.querySelector(".gallery"),l=document.querySelector(".load-btn");let d=1,S="";m.addEventListener("submit",q);l.addEventListener("click",P);async function q(s){s.preventDefault();const r=w.value.trim();if(p.innerHTML="",r===""){n.show({title:"Error",message:"Please enter a search query"});return}c.classList.add("visible");try{const a=(await u.get("/api/",{params:{q:r,page:d}})).data;f(a.hits)}catch{n.error({title:"Error fetching data",message:"An error occurred while fetching data. Please try again later."})}finally{c.classList.remove("visible")}}async function P(){const s=S;c.classList.add("visible");try{const i=(await u.get("/api/",{params:{q:s,page:++d}})).data;f(i.hits)}catch{n.error({title:"Error fetching data",message:"An error occurred while fetching data. Please try again later."})}finally{c.classList.remove("visible")}}function E(s,r,i,a,e,t,o){return`<li class="photo">
    <div class="photo-card">
      <a class="image-link" data-lightbox="image" href="${r}">
        <img class="gallery-image" data-source="${r}" src="${s}" alt="${i}"></img>
      </a>
    </div>
    <div class="description">
      <p class="description-item"> Likes ${a}</p>
      <p class="description-item"> Views ${e}</p>
      <p class="description-item"> Comments ${t}</p>
      <p class="description-item"> Downloads ${o}</p>
    </div>
  </li>`}function f(s){$(),s.length===0&&d===1?(n.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"white",messageSize:"25"}),l.style.visibility="hidden"):l.style.visibility="visible",s.forEach(r=>{const{webformatURL:i,largeImageURL:a,tags:e,likes:t,views:o,comments:g,downloads:y}=r,h=E(i,a,e,t,o,g,y);p.insertAdjacentHTML("beforeend",h)}),L.refresh()}function $(){m.reset()}l.style.visibility="hidden";
//# sourceMappingURL=commonHelpers.js.map
